# **Data Structures, Functions, Numpy & Pandas**

In [ ]:
#SECTION A #

In [ ]:
#1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [56]:
L = [2,8.9,34,1090,2.8794]
D = [2,34,56,78]
L.append(90928)
print('Appended list is :',L)  #Adds item at the last and only one arguement can be passed

L.extend(D)            #adds items from another list or also can pass the numbers directly in the form of list
print('Extended list is :',L)
L.extend([6.7,8.9])
L

L.insert(2,9089098)
print('Inserted list is :' ,L)

L.remove(2)                    # removes 1st matching item passed
print('Removed list is :',L)

L.pop(3)                      # removes and returns the item at the given index , index is passed
print('Popped list is :',L)

L.clear()             #clears everything
print('cleared list :',L)

A = [1,6,2,3,4,5,6]    #finds the index of the item passed
print('indexed item is :',A.index(5))

A.count(6)           #finds how many times number appeared
print('counted item is :',A.count(6))

A.sort()             #sorts in ascending order
print('sorted list is :',A)

A.reverse()            # reverse the list
print('reversed list is :',A)

Appended list is : [2, 8.9, 34, 1090, 2.8794, 90928]
Extended list is : [2, 8.9, 34, 1090, 2.8794, 90928, 2, 34, 56, 78]
Inserted list is : [2, 8.9, 9089098, 34, 1090, 2.8794, 90928, 2, 34, 56, 78, 6.7, 8.9]
Removed list is : [8.9, 9089098, 34, 1090, 2.8794, 90928, 2, 34, 56, 78, 6.7, 8.9]
Popped list is : [8.9, 9089098, 34, 2.8794, 90928, 2, 34, 56, 78, 6.7, 8.9]
cleared list : []
indexed item is : 5
counted item is : 2
sorted list is : [1, 2, 3, 4, 5, 6, 6]
reversed list is : [6, 6, 5, 4, 3, 2, 1]


In [ ]:
#2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [57]:
Students_names = ('Jahnavi', 'Telsang','Priya')
Students_names
Students_names[1] = 'Gowri'         #TypeError: 'tuple' object does not support item assignment
#since the tuple is immutable where the items are not changable however you can convert it to list , change it and then chnage it back to tuple

TypeError: 'tuple' object does not support item assignment

In [58]:
#3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [59]:
s = {23,89,46,19,76,23,46,23}
s
                                 # it prints only the unique vales and duplicates are removed and also every time the output can be in diff order

{19, 23, 46, 76, 89}

In [60]:
b = set([12,23,345,67]) #using set constructor
b

{12, 23, 67, 345}

In [ ]:
#4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [61]:
d = {'name':'jahnavi','age':22,'city':'bangalore'}
d.update({'age':26,'email':'something@gmail.com'})
d

{'name': 'jahnavi',
 'age': 26,
 'city': 'bangalore',
 'email': 'something@gmail.com'}

In [ ]:
#Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [62]:
age = int(input('Enter your age :'))
if age>=18:
    print('You are eligible to vote')
else:
    print('You are not eligible to vote')

Enter your age :13
You are not eligible to vote


In [ ]:
#6.	Given a 'marks' variable, print the grade:- 90 and above: 'A' - 75–89: 'B' - 50–74: 'C' - Below 50: 'Fail'


In [67]:
marks = int(input('Enter your marks : '))
if marks>=90:
    print('A')
elif marks>=75:
    print('B')
elif marks>=50:
      print('C')
else:
      print('Fail')

Enter your marks : 49
Fail


In [ ]:
#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [78]:
num = int(input('Enter a number : '))
if num>0:
    print('The number is positive')
    if num%2==0:
        print('The number is also even')
    else:
        print('The number is odd')
elif num == 0:
  print('The numebr is zero')
else:
  print('The number is negative')

Enter a number : 890
The number is positive
The number is also even


In [ ]:
#8.	Create:- A scalar using np.array(5) - A 1D array with values 1 to 5 - A 2D array (2x3) with values from 10 to 60 in steps of 10


In [85]:
import numpy as np
scalar = np.array(5)
scalar



array(5)

In [86]:
array_id = np.array([1,2,3,4,5])
array_id



array([1, 2, 3, 4, 5])

In [87]:
array_2d = np.array([[10,20,30],[40,50,60]])
array_2d

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [90]:
import random
X = np.random.randint(0,100,(4,4))
X

array([[62, 39,  1, 24],
       [97, 70, 19, 27],
       [18, 60, 49, 45],
       [13, 30, 20, 11]])

In [ ]:
#10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [96]:
import pandas as pd
array_2ds = np.array([[10,20,30],[40,50,60],[70,80,90]])
df = pd.DataFrame(array_2ds,columns = ['A','B','C'])
df


,A,B,C
0,10,20,30
1,40,50,60
2,70,80,90


In [ ]:
#11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
#- Use .info(), .describe()
#- Select 'Name' and 'City' columns
#- Drop 'City' column
#- Fill any missing values in 'Salary' column with the mean
#- Remove any duplicate rows


In [103]:
data = {
    'Name':['Jahnavi','Bob','Alice','Raju','Geeta','Sita','Ram','Lakshman','Ravan','Arjun'],
    'Age':[22,34,45,56,67,78,89,90,76,65],
    'City':['Bangalore','Delhi','Mumbai','Chennai','Bangalore','Delhi','Mumbai','Chennai','Bangalore','Delhi'],
    'Salary':[20000,30000,40000,50000,60000,70000,80000,90000,100000,24000]
}
df = pd.DataFrame(data)
df


,Name,Age,City,Salary
0,Jahnavi,22,Bangalore,20000
1,Bob,34,Delhi,30000
2,Alice,45,Mumbai,40000
3,Raju,56,Chennai,50000
4,Geeta,67,Bangalore,60000
5,Sita,78,Delhi,70000
6,Ram,89,Mumbai,80000
7,Lakshman,90,Chennai,90000
8,Ravan,76,Bangalore,100000
9,Arjun,65,Delhi,24000


In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [105]:
df.describe()

,Age,Salary
count,10.000000,10.000000
mean,62.200000,56400.000000
std,22.870651,28218.197438
min,22.000000,20000.000000
25%,47.750000,32500.000000
50%,66.000000,55000.000000
75%,77.500000,77500.000000
max,90.000000,100000.000000


In [108]:
df[['Name','City']]

,Name,City
0,Jahnavi,Bangalore
1,Bob,Delhi
2,Alice,Mumbai
3,Raju,Chennai
4,Geeta,Bangalore
5,Sita,Delhi
6,Ram,Mumbai
7,Lakshman,Chennai
8,Ravan,Bangalore
9,Arjun,Delhi


In [109]:
df.drop('City',axis=1)

,Name,Age,Salary
0,Jahnavi,22,20000
1,Bob,34,30000
2,Alice,45,40000
3,Raju,56,50000
4,Geeta,67,60000
5,Sita,78,70000
6,Ram,89,80000
7,Lakshman,90,90000
8,Ravan,76,100000
9,Arjun,65,24000


In [111]:
df['Salary'].mean()          #1st find the mean salary and then replace it
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df

,Name,Age,City,Salary
0,Jahnavi,22,Bangalore,20000
1,Bob,34,Delhi,30000
2,Alice,45,Mumbai,40000
3,Raju,56,Chennai,50000
4,Geeta,67,Bangalore,60000
5,Sita,78,Delhi,70000
6,Ram,89,Mumbai,80000
7,Lakshman,90,Chennai,90000
8,Ravan,76,Bangalore,100000
9,Arjun,65,Delhi,24000


In [112]:
duplicates = df.drop_duplicates()
duplicates

,Name,Age,City,Salary
0,Jahnavi,22,Bangalore,20000
1,Bob,34,Delhi,30000
2,Alice,45,Mumbai,40000
3,Raju,56,Chennai,50000
4,Geeta,67,Bangalore,60000
5,Sita,78,Delhi,70000
6,Ram,89,Mumbai,80000
7,Lakshman,90,Chennai,90000
8,Ravan,76,Bangalore,100000
9,Arjun,65,Delhi,24000
